@API_URL = http://localhost:5000

###

GET {{API_URL}}/users

###

POST {{API_URL}}/users
content-type:  application/json

{ "name": "Jonatan db", "email": "jonatan_db@gmail.com", "password": "asd123" }